bind 0.0.0.0
protected-mode yes
port 6379

################################
# 安全
################################
requirepass Longmao!666

################################
# 内存 & 淘汰策略
################################
maxmemory 4gb
maxmemory-policy allkeys-lru

################################
# 持久化（实盘建议开启）
################################
appendonly yes
appendfsync everysec

save 900 1
save 300 10
save 60 10000

################################
# 性能优化
################################
tcp-keepalive 60
timeout 0
databases 16

################################
# 日志
################################
loglevel notice
