# 生产环境配置
env: prod

logging:
    level: DEBUG # DEBUG WARNING INFO
    format: json
    console: false

data:
    catalog_dir: data/processed/catalog
    raw_dir: data/raw
    features_dir: data/features

redis:
    host: "127.0.0.1"
    port: 6379
    db: 0

cache:
    enabled: true
    database: redis
    live:
        flush_on_start: true
    backtest:
        use_instance_id: true
        flush_on_start: false

monitoring:
    enabled: true
    prometheus_port: 9100

risk:
    enabled: true
    mode: hard

exchange:
    environment: LIVE

execution:
    submit_orders: true

live:
    strategy_config: configs/strategies/market_maker.yaml
    universe_top_n: 200
    exclude_stablecoin_bases: true
